title: CTF Writeups & Projects
description: A collection of CTF writeups, security research, and project documentation
baseurl: "/HeyImNas.github.io"
url: "https://HeyImNas.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections for different types of content
collections:
  hackthebox:
    output: true
    permalink: /hackthebox/:name
  tryhackme:
    output: true
    permalink: /tryhackme/:name
  picoctf:
    output: true
    permalink: /picoctf/:name
  projects:
    output: true
    permalink: /projects/:name

# Default layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default" 